### ISSUE TITLE
Multiple revisions of same layoff in WI data

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-transformer#64]
Think there's going to be a lot of this sort of thing to clean up:

<img width="919" alt="Screen Shot 2022-02-21 at 3 57 48 PM" src="https://user-images.githubusercontent.com/1103467/155025565-a1bbf46b-f9b3-4255-af41-c476df6d3584.png">

<img width="706" alt="Screen Shot 2022-02-21 at 3 58 18 PM" src="https://user-images.githubusercontent.com/1103467/155025569-86546f54-59b2-4870-870c-b7f75f894f9d.png">

**Comment by palewire** [comment]
If the state's raw data has an amendment column, could we use that to strike certain records?

**Comment by palewire** [comment]
Another thought, would a true/false boolean called something like `is_amendment` be a reasonable way to start flagging these?

**Comment by palewire** [comment]
Take a look at #68, @chriszs

**Comment by chriszs** [comment]
Yeah, good start! I think what we really want to know is something was _amended_, but obviously harder to flag.

**Comment by chriszs** [comment]
In Wisconsin's case, revisions seem to always appear below the original, could be used to exclude records superseded by amendments.

<img width="645" alt="Screen Shot 2022-02-21 at 8 17 25 PM" src="https://user-images.githubusercontent.com/1103467/155045734-e18dab15-f5dd-4f7b-87ec-7530848596ca.png">

**Comment by palewire** [comment]
Hmm. There must be some way to suds this out.

**Comment by chriszs** [comment]
I think it's going to be a state-by-state fight. It's pretty clear to me how to proceed in WI, but other states may not be so straightforward.

**Comment by palewire** [comment]
Gotcha. I think a first step is to go state by state and try to mark amendments. I'm going to try that first, and then we can figure out how to handle them next.

**Comment by palewire** [comment]
I went through all of the CSV files. I only found one other state — Iowa — that had a clear and obvious indicator of an amendment. That was added here https://github.com/biglocalnews/warn-transformer/pull/69

Have you see other states where you know there to be amendments, @chriszs?

I wonder if @zstumgoren has some wisdom for us here, as well.

**Comment by palewire** [comment]
I've drafted an addition to our transformer system for excluding the ancestors of amendments. You can find that [here](https://github.com/biglocalnews/warn-transformer/pull/71/files#diff-d93dbe243530ecd758bb72a49af2ffd8f0eeb9bebfbda313449dbcba3af603be). It encodes what are my latest opinions on WI and IA. For WI, it strikes the previous record in the sheet if the name is the same. For IA, it does nothing, because I can't spot any duplication introduced by the amendments.

**Comment by chriszs** [comment]
IL comes to mind because I did that recently.

**Comment by zstumgoren** [comment]
Hey @palewire I hadn't noticed amendments in other states, but I'd defer to you and @chriszs at this point on where else this may apply. I *do* like the strategy of giving precedence to the most recently filed amendment, which feels very much in line with how FEC filings work. Alas, sounds like WARN-land we need to devise a heuristic for identifying related records in an "amendment chain". @palewire Am I reading your PR correctly that the v1 strategy is based primarily on identification of a repeated company name?

**Comment by palewire** [comment]
@zstumgoren, yes, the Wisconsin system is based on three factors: the revised flag, the sort order and the company name. It passes my eyeball test.

I'm considering it have it throw a hard error rather than a log when no ancestor filing is found. That might prevent some new data entry practice from the state introducing silent bugs. 

The policy is limited to WI this far. The code is th current PR wouldn't affect anywhere else.

**Comment by palewire** [comment]
@chriszs, when you have a minute can you point out to me what you see in the IL data?

In the meantime, I am going to merge this PR.

**Comment by chriszs** [comment]
So this may be moot if the state's live data portal provides a better alternative to the archive page we're using (I've put this in a ticket), but archive has these supplemental notices at bottom of sheets:

<img width="1303" alt="Screen Shot 2022-02-22 at 3 40 00 PM" src="https://user-images.githubusercontent.com/1103467/155215572-1de22127-cb64-4075-949f-8fd0eada0532.png">

Employee number is additional, so may not inflate that, but unclear whether handling this well in every case.

**Comment by palewire** [comment]
I think we got this handled. Correct me if we dont.
