### ISSUE TITLE
We expect IA duplicates

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-transformer#65]
As described here https://github.com/biglocalnews/warn-scraper/issues/435

**Comment by palewire** [comment]
I think we will see overlaps in 2017 and 2018

**Comment by chriszs** [comment]
I wonder if this shouldn't be the rare case where the scraper filters for data quality because it knows which records come from which file, so can merely do a cutoff on a year.

**Comment by palewire** [comment]
Could be. We do have a duplicate checker here already https://github.com/biglocalnews/warn-transformer/blob/main/warn_transformer/consolidate.py#L38

I'm also open to the idea of a file validator step in each state's transformers that allows for integrity checks across multiple fields within a row, as well as checks that span multiple rows.

**Comment by palewire** [comment]
Let me know what you think of this technique, @chriszs https://github.com/biglocalnews/warn-transformer/pull/66

**Comment by chriszs** [comment]
I think that's an improvement! Doesn't address every case (e.g., not #64), but helps.

**Comment by palewire** [comment]
I think these were handled.
