### ISSUE TITLE
IL incorrect uses total employee field

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-transformer#75]
Believe the correct field is Revised Layoff.

<img width="451" alt="Screen Shot 2022-02-24 at 9 36 47 PM" src="https://user-images.githubusercontent.com/1103467/155644734-0c1f31a2-723b-407a-ac8a-e27db5bb1358.png">
.

**Comment by palewire** [comment]
Is it always filled in?

**Comment by chriszs** [comment]
Yes! Appears to be. I also wondered that, and if it shouldn't have a fallback to "Expected Layoff," but I don't see gaps. Not entirely sure if they're using expected in the interim or what. The app interface has one table column called "Reported Layoffs," which presumably is either one of these or some combination of both.

There's a separate tab in the exported Excel file for "Scheduled Layoffs," ordinarily I'd argue for also including that (which we do in other states), but it has scheduled layoffs going to back to the 90s (unclear if those happened or not, have not researched), so I suspect what we're seeing here is some sort of confirmed set of layoffs.

**Comment by palewire** [comment]
Great
