### ISSUE TITLE
Add a load step

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-transformer#88]
- [ ] Get yesterday's file
- [ ] Get today's file
- [ ] Loop through every source, compare today's hashes to yesterday, when they match exactly nothing has changed and those rows can be put aside. The remaining rows are either new or amended.
- [ ] Loop through the new or amended list and compare each dict against all of yesterday's dict that didn't have an exactly match. In cases where there is a match above a certain fancy threshold to be determined later, these are potential amendment and should be filed seperately. In cases where there is no close match, the records are assumed to be new.
- [ ] New records are added to yesterday's list with a current timestamp
- [ ] Amended records give a customized test based on what we know about the fields. In cases where the fields that have changed suggest it's highly likely the record is amended, we write the amended with an update timestamp.
- [ ] In cases where the field comparison doesn't suggest the record is a likely amendment, we may ask a human to decide if it ought to be filed as new. 
- [ ] Log all new records and all amendments to console, but also maybe Slack, a GitHub Issue, something else. 
- [ ] Write out an updated version of our "loaded.csv" file that has the reconciled database with our additional timestamp metadata columns

**Comment by palewire** [comment]
We might be able to use this for the comparisons https://pypi.org/project/jellyfish/

**Comment by chriszs** [comment]
I also considered training Dedupe to generate candidates.

**Comment by chriszs** [comment]
Tried `csvdedupe` with somewhat frustrating results. Probably could do better with some heuristics.
